package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//sass:sass.bzl", "sass_library")

sass_library(
    name = "modules",
    srcs = ["_all.scss"],
    deps = [
        "acordeon",
        "breadcrumb",
        "card",
        "group",
        "media",
        "mega",
        "menus",
        "message",
        "modal",
        "navbar",
        "notify",
        "slideshow",
        "social",
        "tables",
        "tabs",
        "//kimera/scss/base:partials",
    ],
)

sass_library(
    name = "acordeon",
    srcs = ["_acordeon.scss"],
    deps = [
        "//kimera/scss/base:partials",
        "//kimera/scss/base:placeholders",
    ],
)

sass_library(
    name = "breadcrumb",
    srcs = ["_breadcrumb.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "card",
    srcs = ["_card.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "group",
    srcs = ["_group.scss"],
    deps = [
        "//kimera/scss/base:partials",
        "//kimera/scss/base:placeholders",
    ],
)

sass_library(
    name = "media",
    srcs = ["_media.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "mega",
    srcs = ["_mega.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "menus",
    srcs = ["_menus.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "message",
    srcs = ["_message.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "modal",
    srcs = ["_modal.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "navbar",
    srcs = ["_navbar.scss"],
    deps = [
        "//kimera/scss/base:partials",
        "//kimera/scss/base:placeholders",
    ],
)

sass_library(
    name = "notify",
    srcs = ["_notify.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "slideshow",
    srcs = ["_slideshow.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "social",
    srcs = ["_social.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "tables",
    srcs = ["_tables.scss"],
    deps = ["//kimera/scss/base:partials"],
)

sass_library(
    name = "tabs",
    srcs = ["_tabs.scss"],
    deps = ["//kimera/scss/base:partials"],
)
